void testfunc(void);
void inputVec(double *inp, int num);
void printVec(double *inp, int num);
double sumVec(double *dp, int num);
double averageVec(double *dp, int num);
void calc_absVec(double *inp, double *outp, int num);
void calc_squareVec(double *inp, double *outp, int num);
void cmulVec(double *outp, double *inp, double k, int num);
void addVec(double *outp, double *inp1, double *inp2, int num);
void subVec(double *outp, double *inp1, double *inp2, int num);
void mulVec(double *outp, double *inp1, double *inp2, int num);
double innerVec(double *inp1, double *inp2, int num);
double calcLen(double *dp, int num);
void printVecRow(double *dp, int num);
void uniVec(double *inp, double *outp, int num);
